"""Complete bilingual product wording; scientific claims are identical by key."""

from __future__ import annotations


LABELS = {
    "ja": {
        "app.title": "Harako-GPU — reference-aware GUI",
        "local_only": "ローカル専用。研究用途のみ・診断／臨床用途ではありません。",
        "project": "プロジェクト", "samples": "サンプル", "reference": "参照配列と実行可否",
        "analysis": "解析", "review": "確認と準備", "run": "実行",
        "results": "結果", "recovery": "復旧とサポート",
        "quant_only": "発現定量のみ", "bam_keep": "BAMを作成", "bam_discard": "検証後にBAM削除",
        "available": "利用可能", "limited": "制限付きで利用可能",
        "unavailable": "このPCでは利用不可", "unqualified": "未検証",
        "recommended": "再現性優先・推奨", "compatibility": "互換性優先", "compare": "両方式を比較",
        "quant.copy": "この解析ではFASTQから発現定量のみを行います。BAM、splice junction、STAR GeneCountsは生成しません。Salmon定量はCPU処理であり、GPUは使用しません。",
        "human.blocked": "このPCでは、選択されたhuman referenceを用いたGPU BAM生成がhost RAMの検証済み範囲を超えるため、実行できません。BAMなしの発現定量は利用できます。BAMが必要な場合は、高メモリGPU環境向けhandoffを作成してください。",
        "compare.copy": "2つのSalmon profileの差は、解析方法やversionへの感度を示します。一方を誤りと判定するものではありません。primary profileだけが将来のdownstream解析へ使用されます。",
        "no_cancel": "停止／cancelはMVPでは未実装です。browserを閉じてもrunは継続します。failure／interruption時はresumeを使用してください。",
        "language": "言語", "navigation": "ナビゲーション",
        "purpose": "このページの目的", "completion": "完了条件", "current_blocker": "現在のblocker",
        "details": "技術詳細", "next_action": "次の操作", "error_summary": "修正が必要な項目",
        "level.info": "情報", "level.limitation": "制限", "level.warning": "注意",
        "level.blocker": "実行不可", "level.failure": "失敗",
        "page.project.purpose": "解析を保存するprojectと安全なruntime領域を決めます。",
        "page.project.complete": "有効なproject slugとruntime／output／work rootが設定されていること。",
        "page.samples.purpose": "FASTQをscanし、sample、read pair、library typeを確認します。",
        "page.samples.complete": "orphanや重複がなく、全sampleが検証済みであること。",
        "page.reference.purpose": "referenceを選び、このPCで利用できる解析routeを確認します。",
        "page.reference.complete": "利用可能なrouteが明示的に選択されていること。",
        "page.analysis.purpose": "発現定量profileとprimary結果を選びます。",
        "page.analysis.complete": "quantification modeとprimary profileが確定していること。",
        "page.review.purpose": "入力、route、BAM、GPU、reference、profileを確認し、変更不能なrunを準備します。",
        "page.review.complete": "capabilityが利用可能で、immutable runとapproval hashが作成されていること。",
        "page.run.purpose": "準備済みrunを承認し、進捗と安全な次の操作を確認します。",
        "page.run.complete": "terminal stateとrequired artifact validationが確定すること。",
        "page.results.purpose": "生成されたもの、生成されなかったもの、primary結果と制限を確認します。",
        "page.results.complete": "validated artifactとself-contained reportを確認すること。",
        "page.recovery.purpose": "failure evidenceを確認し、support bundleまたは安全なresumeを利用します。",
        "page.recovery.complete": "failure evidenceを保存し、resumeまたはnew prepareの次actionが決まること。",
        "glossary.fastq": "FASTQはsequencerから得たread配列とqualityを保存する入力fileです。",
        "glossary.bam": "BAMはreadをgenome上の位置へ対応付けたalignment fileです。",
        "glossary.tpm": "TPMはsample内でtranscript／gene abundanceを比較する正規化値です。",
        "glossary.gpu": "GPUは対応routeのgenome alignmentを加速します。Salmon発現定量はCPU処理です。",
        "generated": "生成されたもの", "not_generated": "生成されなかったもの",
        "primary_result": "Primary結果", "comparison_only": "Comparison専用secondary",
        "auto_refresh": "自動更新", "refresh_interval": "更新間隔", "refresh_now": "今すぐ更新",
        "polling_paused": "自動更新は一時停止中です。run自体は継続しています。",
        "stale_status": "最後に正常取得したstatusを表示しています。bounded retryを継続します。",
        "prepare_run": "変更不能なrunを準備", "start_run": "実行開始", "review_confirm": "変更不能なrun内容を確認しました",
        "select": "選択", "unavailable_planned": "今後対応予定（選択不可）",
        "human_bam.next": "BAMなしの発現定量を選ぶか、高メモリGPU環境向けhandoffを作成してください。",
        "samples.next": "表示されたfieldを修正し、FASTQを再scanしてください。",
        "prepared.next": "approval hashを確認してRunページから開始してください。",
        "results.pending": "runはまだ完了していません。partial scientific artifactは通常結果として表示しません。",
        "profile.secondary": "secondaryは方法依存性の比較専用で、将来のdownstream解析へ自動使用されません。",
        "browser_continues": "browser tabを閉じてもactive runは継続します。",
        "artifact.processed_fastq": "処理済みFASTQ", "artifact.transcript_counts": "transcript counts",
        "artifact.transcript_tpm": "transcript TPM", "artifact.gene_counts": "gene counts",
        "artifact.gene_tpm": "gene TPM", "artifact.report": "self-contained report",
        "artifact.concordance": "profile concordance", "artifact.bam_bai": "BAM／BAI",
        "artifact.junctions": "splice junction", "artifact.star_counts": "STAR GeneCounts",
        "artifact.multiqc": "alignment MultiQC", "artifact.gpu_evidence": "GPU alignment evidence",
        "blocker.project": "projectを選択または作成してください。",
        "blocker.samples": "sampleを検証してください。", "blocker.route": "利用可能なrouteを選択してください。",
        "blocker.prepare": "先にrunを準備してください。", "blocker.run": "runを選択してください。",
    },
    "en": {
        "app.title": "Harako-GPU — reference-aware GUI",
        "local_only": "Local-only. Research use only; non-diagnostic and non-clinical.",
        "project": "Project", "samples": "Samples", "reference": "Reference & capability",
        "analysis": "Analysis", "review": "Review & prepare", "run": "Run",
        "results": "Results", "recovery": "Recovery & support",
        "quant_only": "Expression quantification only", "bam_keep": "Generate BAM", "bam_discard": "Discard BAM after validation",
        "available": "Available", "limited": "Available with limitations",
        "unavailable": "Unavailable on this host", "unqualified": "Not qualified",
        "recommended": "Reproducibility-first — recommended", "compatibility": "Compatibility-first", "compare": "Compare both",
        "quant.copy": "This analysis performs expression quantification directly from FASTQ. BAM, splice-junction, and STAR GeneCounts artifacts are not generated. Salmon quantification is CPU-based; the GPU was not used in this route.",
        "human.blocked": "This PC cannot generate GPU BAM for the selected human reference because it exceeds the qualified host-memory envelope. Expression quantification without BAM is available. Create a high-memory GPU host handoff if BAM is required.",
        "compare.copy": "Differences between the two Salmon profiles indicate sensitivity to method or version; they do not label either result as wrong. Only the primary profile is eligible for future downstream analysis.",
        "no_cancel": "Stop/cancel is not implemented in this MVP. Closing the browser does not stop a run. Use resume after failure or interruption.",
        "language": "Language", "navigation": "Navigation",
        "purpose": "Purpose of this page", "completion": "Completion condition", "current_blocker": "Current blocker",
        "details": "Technical details", "next_action": "Next action", "error_summary": "Items requiring correction",
        "level.info": "Information", "level.limitation": "Limitation", "level.warning": "Warning",
        "level.blocker": "Blocked", "level.failure": "Failure",
        "page.project.purpose": "Choose the project and safe runtime area for this analysis.",
        "page.project.complete": "A valid project slug and runtime, output, and work roots are set.",
        "page.samples.purpose": "Scan FASTQ files and confirm samples, read pairs, and the library type.",
        "page.samples.complete": "All samples are validated with no orphan or duplicate reads.",
        "page.reference.purpose": "Choose a reference and check which analysis routes this PC can run.",
        "page.reference.complete": "An available route is selected explicitly.",
        "page.analysis.purpose": "Choose the expression-quantification profile and primary result.",
        "page.analysis.complete": "The quantification mode and primary profile are fixed.",
        "page.review.purpose": "Review inputs, route, BAM, GPU, reference, and profiles, then prepare an immutable run.",
        "page.review.complete": "Capability is available and an immutable run with an approval hash is prepared.",
        "page.run.purpose": "Approve a prepared run and monitor progress and safe next actions.",
        "page.run.complete": "A terminal state and required-artifact validation are established.",
        "page.results.purpose": "Understand what was and was not generated, the primary result, and limitations.",
        "page.results.complete": "Validated artifacts and the self-contained report have been reviewed.",
        "page.recovery.purpose": "Review failure evidence and use a support bundle or safe resume.",
        "page.recovery.complete": "Failure evidence is preserved and the next action is resume or a new preparation.",
        "glossary.fastq": "FASTQ stores sequencer reads and their quality scores as input files.",
        "glossary.bam": "BAM stores reads aligned to positions in a genome.",
        "glossary.tpm": "TPM is a normalized abundance value for comparing transcripts or genes within a sample.",
        "glossary.gpu": "The GPU accelerates genome alignment on supported routes. Salmon expression quantification is CPU-based.",
        "generated": "Generated", "not_generated": "Not generated",
        "primary_result": "Primary result", "comparison_only": "Comparison-only secondary",
        "auto_refresh": "Auto refresh", "refresh_interval": "Refresh interval", "refresh_now": "Refresh now",
        "polling_paused": "Auto refresh is paused. The run itself continues.",
        "stale_status": "Showing the last valid status while bounded retry continues.",
        "prepare_run": "Prepare immutable run", "start_run": "Start run", "review_confirm": "I reviewed the immutable run contract",
        "select": "Select", "unavailable_planned": "Planned for later (not selectable)",
        "human_bam.next": "Choose expression quantification without BAM or create a high-memory GPU host handoff.",
        "samples.next": "Correct the listed fields and scan the FASTQ files again.",
        "prepared.next": "Review the approval hash and start from the Run page.",
        "results.pending": "The run is not complete. Partial scientific artifacts are not presented as normal results.",
        "profile.secondary": "The secondary profile is for method-sensitivity comparison only and is not automatically used for future downstream analysis.",
        "browser_continues": "Closing the browser tab does not stop an active run.",
        "artifact.processed_fastq": "Processed FASTQ", "artifact.transcript_counts": "Transcript counts",
        "artifact.transcript_tpm": "Transcript TPM", "artifact.gene_counts": "Gene counts",
        "artifact.gene_tpm": "Gene TPM", "artifact.report": "Self-contained report",
        "artifact.concordance": "Profile concordance", "artifact.bam_bai": "BAM / BAI",
        "artifact.junctions": "Splice junctions", "artifact.star_counts": "STAR GeneCounts",
        "artifact.multiqc": "Alignment MultiQC", "artifact.gpu_evidence": "GPU alignment evidence",
        "blocker.project": "Choose or create a project.",
        "blocker.samples": "Validate the samples.", "blocker.route": "Select an available route.",
        "blocker.prepare": "Prepare a run first.", "blocker.run": "Select a run.",
    },
}


def text(key: str, language: str) -> str:
    try:
        return LABELS[language][key]
    except KeyError as exc:
        raise ValueError(f"Missing GUI translation: {language}/{key}") from exc


def assert_complete() -> None:
    if set(LABELS) != {"ja", "en"} or set(LABELS["ja"]) != set(LABELS["en"]):
        raise ValueError("Japanese and English GUI label catalogs must have identical keys")


def page_label(page: str, language: str) -> str:
    key = {
        "Project": "project", "Samples": "samples", "Reference & capability": "reference",
        "Analysis": "analysis", "Review & prepare": "review", "Run": "run",
        "Results": "results", "Recovery & support": "recovery",
    }.get(page)
    if key is None:
        raise ValueError(f"Unknown GUI page: {page}")
    return text(key, language)
